from django.shortcuts import render

ingredients = {
    "Avocado": None,
    "Bean sprouts": None,
    "Beef": None,
    "Bell peppers": None,
    "Breadcrumbs": None,
    "Broccoli florets": None,
    "Butter": None,
    "Cabbage": None,
    "Carrots": None,
    "Celery": None,
    "Cheddar cheese": None,
    "Chicken": None,
    "Chili powder": None,
    "Cilantro": None,
    "Cocoa powder": None,
    "Corn tortillas": None,
    "Cumin": None,
    "Curry powder": None,
    "Diced tomatoes": None,
    "Dried red chilies": None,
    "Dumpling wrappers": None,
    "Eggs": None,
    "Extra virgin olive oil": None,
    "Fettuccine pasta": None,
    "Fish sauce": None,
    "Flour": None,
    "Fresh basil": None,
    "Fresh mozzarella": None,
    "Fresh tomatoes": None,
    "Garlic": None,
    "Gochujang": None,
    "Gouda cheese": None,
    "Green onions": None,
    "Ground beef": None,
    "Ground chicken": None,
    "Ground shrimp": None,
    "Honey glaze": None,
    "Italian herbs": None,
    "Jalapeño": None,
    "Lemon": None,
    "Lemon juice": None,
    "Linguine pasta": None,
    "Macaroni": None,
    "Mascarpone cheese": None,
    "Mirin": None,
    "Mushrooms": None,
    "Olive oil": None,
    "Onions": None,
    "Oyster sauce": None,
    "Parmesan cheese": None,
    "Pasta": None,
    "Peanut butter": None,
    "Peanuts": None,
    "Pepper": None,
    "Red chilies": None,
    "Red onion": None,
    "Red pepper flakes": None,
    "Rice": None,
    "Rice noodles": None,
    "Romaine lettuce": None,
    "Sake": None,
    "Salt": None,
    "Sesame oil": None,
    "Sesame seeds": None,
    "Short-grain rice": None,
    "Shrimp": None,
    "Soy sauce": None,
    "Spinach": None,
    "Sugar": None,
    "Tamarind paste": None,
    "Tofu": None,
    "Tomato paste": None,
    "White sugar": None,
    "White wine": None
}


def index(request):